services:
  - type: web
    name: didactic-guacamole
    runtime: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt gevent==26.4.0
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --worker-class gevent --worker-connections 100 --timeout 120 --max-requests 1000 --max-requests-jitter 100
    autoDeployTrigger: commit

  - type: cron
    name: didactic-guacamole-results-cron
    runtime: python
    region: oregon
    plan: starter
    branch: main
    schedule: "*/5 * * * *"
    buildCommand: pip install -r requirements.txt
    startCommand: python scraper/scrape_and_save.py
    autoDeployTrigger: commit

