package com.lotterynet.pro.core.model

data class UserAccount(
    val id: String,
    val user: String,
    val role: UserRole,
    val displayName: String? = null,
    val ownerName: String? = null,
    val address: String? = null,
    val active: Boolean = true,
    val adminId: String? = null,
    val adminUser: String? = null,
    val banca: String? = null,
    val cashierPrefix: String? = null,
    val createdLabel: String? = null,
    val territory: String? = null,
    val phone: String? = null,
    val balance: Double = 0.0,
    val rechargesEnabled: Boolean = false,
    val rechargesAssignedBalance: Double = 0.0,
    val rechargesBalance: Double = 0.0,
    val recargasRapidasUsername: String? = null,
    val recargasRapidasPassword: String? = null,
    val commissionRate: Double? = null,
    val recargaTxLimit: Double? = null,
    val supervisorIds: List<String> = emptyList(),
    val supervisorUsers: List<String> = emptyList(),
    val lastSeenAtEpochMs: Long? = null,
    val passwordSalt: String? = null,
    val passwordHash: String? = null,
    val passwordVersion: String? = null,
    val authUserId: String? = null,
    val credChangedAtEpochMs: Long? = null,
    val updatedAtEpochMs: Long? = null,
    val systemModeOverride: String? = null,
)
