do $$
declare
  target_table record;
  qualified_table text;
  pk_name text;
begin
  for target_table in
    select * from (values
      ('lotterynet_backup'::text, 'ticket_items_20260529_0227'::text),
      ('lotterynet_backup'::text, 'lotterynet_results_by_day_20260529_0227'::text),
      ('lotterynet_backup'::text, 'backup_manifest_20260529_0227'::text),
      ('lotterynet_backup'::text, 'lotterynet_pick_results_by_day_20260529_0227'::text),
      ('public'::text, 'lotterynet_tickets_by_owner_backup_empty_items_20260529'::text),
      ('lotterynet_backup'::text, 'movimientos_balance_20260529_0227'::text),
      ('lotterynet_backup'::text, 'lotterynet_kv_results_20260529_0227'::text),
      ('lotterynet_backup'::text, 'tickets_20260529_0227'::text),
      ('lotterynet_backup'::text, 'pagos_20260529_0227'::text)
    ) as t(schema_name, table_name)
  loop
    if to_regclass(format('%I.%I', target_table.schema_name, target_table.table_name)) is null then
      continue;
    end if;

    qualified_table := format('%I.%I', target_table.schema_name, target_table.table_name);
    pk_name := left(target_table.table_name || '_backup_row_id_pk', 63);

    execute format(
      'alter table %s add column if not exists backup_row_id bigint generated by default as identity',
      qualified_table
    );

    if not exists (
      select 1
      from pg_index i
      join pg_class c on c.oid = i.indrelid
      join pg_namespace n on n.oid = c.relnamespace
      where i.indisprimary
        and n.nspname = target_table.schema_name
        and c.relname = target_table.table_name
    ) then
      execute format(
        'alter table %s add constraint %I primary key (backup_row_id)',
        qualified_table,
        pk_name
      );
    end if;
  end loop;
end $$;
